# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 提笔
subtitle: 提笔忘字，贵人忘事
description: 提笔忘字，贵人忘事
keywords: 提笔忘字，贵人忘事
author: tibi.vip
language: zh-CN
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://tibi.vip
root: /
permalink: :category/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: hexo-theme-next-7.5.0
# _config.yml
theme_config:
  auto_excerpt:
    enable: true
    length: 150
  minify: true
  rss: false
  footer:
    # Specify the date when the site was setup. If not defined, current year will be used.
    since: 2019
    # If not defined, `author` from Hexo `_config.yml` will be used.
    copyright: tibi.vip<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script><script>(adsbygoogle = window.adsbygoogle || []).push({google_ad_client:"ca-pub-1724510281321048",enable_page_level_ads:true});</script>

    powered:
      # Hexo link (Powered by Hexo).
      enable: false
      # Version info of Hexo after Hexo link (vX.X.X).
      version: fasle

    theme:
      # Theme & scheme info link (Theme - NexT.scheme).
      enable: false
      # Version info of NexT after scheme info (vX.X.X).
      version: false
  menu:
    home: / || home
    tags: /tags/ || tags
    categories: /categories/ || th
    archives: /archives/ || archive
    # schedule: /schedule/ || calendar
    # sitemap: /sitemap.xml || sitemap
    # commonweal: /404/ || heartbeat
    about: /about/ || user
  scheme: Gemini
  links:
    人人岐黄网: https://rrtcm.com
  # TagCloud settings for tags page.
  tagcloud:
    # If true, font size, font color and amount of tags can be customized
    enable: true
    # All values below are same as default, change them by yourself
    min: 12 # Minimun font size in px
    max: 30 # Maxium font size in px
    start: "#ccc" # Start color (hex, rgba, hsla or color keywords)
    end: "#111" # End color (hex, rgba, hsla or color keywords)
    amount: 200 # Amount of tags, change it if you have more than 200 tags
  custom_logo: /images/logo.png
  favicon:
    small: /images/favicon-16x16.png
    medium: /images/favicon-32x32.png
    apple_touch_icon: /images/apple-touch-icon.png
    safari_pinned_tab: 
    #android_manifest: /images/manifest.json
    #ms_browserconfig: /images/browserconfig.xml
  # Local Search
  # Dependencies: https://github.com/wzpan/hexo-generator-search
  local_search:
    enable: true
    # If auto, trigger search by changing input.
    # If manual, trigger search by pressing enter key or search button.
    trigger: auto
    # Show top n results per article, show all results by setting to -1
    top_n_per_article: -1
    # Unescape html strings to the readable one.
    unescape: true
    # Preload the search data when the page loads.
    preload: true
utteranc:
  enable: true
  repo: tibi-vip/forum
  pathname: pathname
  # theme: github-light,github-dark,github-dark-orange
  theme: github-light
  cdn: https://utteranc.es/client.js
  # cdn: /files/client.js
  # If you want to modify priority, please config in **hexo**
  #priority:
sitemap:
    path: sitemap.xml
# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://e.coding.net/rrtcm/tibi/tibi.git
  branch: master
  message: hexo deploy
